### ISSUE TITLE
Some question about GitHub interface and feature

### ISSUE THREAD

**Issue by mlipok** [Danp2/AutoIT_FF_Automation#10]
For "NextRelase Branch"   
I see "This branch is 11 commits ahead, **1 commit behind master**."

Is that mean that in Master was commited something and NextRelase was not ?

**Comment by Danp2** [comment]
Yes, likely the ReadMe update done [here](https://github.com/Danp2/AutoIT_FF_Automation/commit/4b8c13e3c332322c4f7da195df82671bb016b7ac).

**Comment by Danp2** [comment]
I rebased the branch so the the Readme file is in sync on the next-release branch. However, the `1 commit behind master` won't go away until the next time next-release is merged into master.

**Comment by mlipok** [comment]
Ok thanks for clarification.
